### ISSUE TITLE
Why does the mod require a Alpha version of JEI? 

### ISSUE THREAD

**Issue by ALainxD** [ApexStudios-Dev/FantasyFurniture#30] opened 2022-08-22 16:42 UTC
And why not stable releases or even Beta?

**Comment by ApexModder** [comment] 2022-08-22 16:45
Duplicate of #29 See that issue for a response.

**Closed by ApexModder** 2022-08-22 16:45 UTC

**Comment by ALainxD** [comment] 2022-08-22 16:51
It's just a bit annoying because the alpha version of JEI doesn't work with Configured so users can't change settings without needing to go into the Files

**Comment by ApexModder** [comment] 2022-08-22 17:25
_Copied from #29_
> We require an alpha version of JEI due to the downports from 1.19.2 using the newer API changes which only exist in the alpha versions on 1.18.2.
> 
> We could go through and change to use more stable version but that would require more work than we want to put into 1.18.2. 1.18.2 is our LTS version, it receives critical bug fixes & downports of finished features from 1.19.2 While 1.19.2 is where we mainly work and make these kinds of changes, and downport the finished state to 1.18.2 when the time comes for it.
---
Noted we may or may not make the changes to use a more stable version, the issue is with how we downport changes from 1.19.2 to 1.18.2.
we would have to make these changes every time we downport a change from 1.19.2, it is just easier to leave it on alpha and continue working on new stuff rather than repeating stuff on every update.
