### ISSUE TITLE
Stuck on Saving world screen

### ISSUE THREAD

**Issue by Answordy** [ApexStudios-Dev/FantasyFurniture#22] opened 2022-06-13 12:42 UTC
Clicking on 'Save and Quit to Title' in a singleplayer breaks the game, you are stuck on the 'Saving world' screen forever and need to force shutdown the game with task manager. The progress isn't always saved models may break and glitch out, other strange bugs appaer (likely because of corrupted world saving)

To replicate the bug:
1. create new singleplayer world
2. grab a furniture from creative inventory (I think only ones that have inventory break the world, chests, bookshelves)
3. place it down (maybe open it idk?)
4. leave the game

mc 1.18.2
forge 40.1.48
curseforge client
no other mods, just Fantasy Furniture and it's dependencies
no texturepacks, no datapacks, etc, fresh mc install

(edit) also log doesn't say anything, no crash reports

**Comment by ApexModder** [comment] 2022-06-13 13:08
Confirmed this is due to the inventory based blocks within the mod. This issue has been marked as `priority` and will be fixed asap.

**Comment by ApexModder** [comment] 2022-06-13 17:43
This issues seems to have been fixed but some rigorous testing will have to be done before we push out an update.
As of right now, we can place one of the inventory block (or 1 of each in my test world) and save, load & quit the game fine without it hanging anymore.

**Comment by ApexModder** [comment] 2022-06-14 03:00
Issue has been resolved and an update will be released asap!

**Closed by ApexModder** 2022-06-14 03:00 UTC
Labels: bug, priority
